### ISSUE TITLE
[어드민컨텐츠] option의 selected 속성 에러

### ISSUE THREAD

**Issue by devjoylee** [numbble/frontend#31]
어드민컨텐츠 페이지가 로드 되면 , 
`Warning: Use the 'defaultValue' or 'value' props on <select> instead of setting 'selected' on <option>.` 
라는 에러메세지가 생깁니다!

**Comment by rachel490** [comment]
넵! 확인하였습니다! 다음 PR에 반영해서 올릴게요~
